from .duplicate_columns import *
from .duplicate_rows import *
from .email_syntax import *
from .handle_na import *
from .is_correct_datatype import *
from .missing_data import *
from .num_outliers import *
from .rule_messages import *
from .str_outlier import *
from .validdate import *
from .wrong_category import *
from .spellcheck import *